### ISSUE TITLE
Audio quality appears capped at 128k

### ISSUE THREAD

**Issue by j0nny55555** [TareqAlqutami/rtmp-hls-server#1]
The aac code doesn't appear to be able to be configured to do more, can we have more audio codecs, such as libmp3lame or something else. I am new to this, but I hope my thoughts find you well. Thank you for this tool, I'm just hoping to really maximize my available bandwidth.

**Comment by TareqAlqutami** [comment]
Dear @j0nny55555,
Sorry I took long to reply.
That is the expected performance in the default configuration file. 
You can modify the bit rate in conf/nginx.conf file and use the modified nginx.conf when you run docker.
`docker run -d -p 1935:1935 -p 8080:8080 -v custom.conf:/etc/nginx/nginx.conf alqutami/rtmp-hls `

On the other hand, I also updated the docker image to support libmp3lame in both Debian and Alpine images. You can modify the codecs in the nginx.conf file and perform and FFmpeg transcoding you wish.

Let me know if you face any other issues.
