### ISSUE TITLE
Audio only in HLS, nothing in DASH -  using NVENC

### ISSUE THREAD

**Issue by ZARk-be** [TareqAlqutami/rtmp-hls-server#12]
Hello

Trying to set this up.
I'm sending from OBS in rtmp successully.
I can open the rtmp stream in VLC .

When loading the HLS player i'm getting audio only, black video.
in dash the spinner is just spinning endlessly.

/stats gives this ; 
`

RTMP | #clients | Video | Audio | In bytes | Out bytes | In bits/s | Out bits/s | State | Time
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
Accepted: 21 | 199.71 MB | 155.95 MB | 2.91 Mb/s | 567 Kb/s |   | 9m 55s
live
live streams | 2
test | 2 | H264 High 4.0 | 2.23 Mb/s | 1920x1080 | 30 | AAC LC | 126 Kb/s | 48000 | 2 | 5.31 MB | 3.06 MB | 2.35 Mb/s | 561 Kb/s | active | 18s
show
live streams | 5
test_hd720 | 1 |   | 0 Kb/s | 0x0 | 0 | AAC LC | 198 Kb/s | 48000 | 2 | 273 KB | 0 KB | 198 Kb/s | 0 Kb/s | active | 11s
test_src | 1 |   | 0 Kb/s | 0x0 | 0 | AAC LC | 197 Kb/s | 48000 | 2 | 271 KB | 0 KB | 197 Kb/s | 0 Kb/s | active | 11s
test_mid | 1 |   | 0 Kb/s | 0x0 | 0 | AAC LC | 198 Kb/s | 48000 | 2 | 273 KB | 0 KB | 198 Kb/s | 0 Kb/s | active | 11s
test_high | 1 |   | 0 Kb/s | 0x0 | 0 | AAC LC | 198 Kb/s | 48000 | 2 | 273 KB | 0 KB | 198 Kb/s | 0 Kb/s | active | 11s
test_low | 1 |   | 0 Kb/s | 0x0 | 0 | AAC LC | 100 Kb/s | 48000 | 2 | 137 KB | 0 KB | 100 Kb/s | 0 Kb/s | active | 12s

`

**Comment by TareqAlqutami** [comment]
I just tested again and the players seem to work. Looking at the stats, there doesn't seem to be any transcoding from rtmp.
Here is a screenshot of when it works:
![image](https://user-images.githubusercontent.com/46659456/100396821-94c84780-3081-11eb-99f7-a19162206cb6.png)

Can you share your config you used to run the container. For html players, can you inspect the browser page to see any console errors

**Comment by ZARk-be** [comment]
ok i investigated further.

Seems like it's the source encoder in OBS.
If i use the hardware NVENC i get the issue, if i switch to software x264 it's working as expected !

Maybe an issue with ffmpeg settings ?

**Comment by TareqAlqutami** [comment]
Yes perhaps, there is a new update in the repo that includes nvenc support. You will need to build the docker image using Dockerfile-nvenc docker file then test the built image using.
`
docker run --rm -it -p 1935:1935 -p 8080:8080 --runtime=nvidia <docker_image_name>
`
I would be happy to hear your feedback.

**Comment by dv4mp1r3** [comment]
Hello.

Got the same issue after building the image (before and after patch.sh update for my driver version)

```
docker run --rm -it -p 1935:1935 -p 8080:8080 --runtime=nvidia c6776b795370
Detected nvidia driver version: 460.32.03
Attention! Backup not found. Copying current libnvidia-encode.so to backup.
27ad5fbdbf706a8e5ba5fe79c8ea0a8235002ff8  /opt/nvidia/libnvidia-encode-backup/libnvidia-encode.so.460.32.03
598c03cf0b86a61e2e9f18d3ad745c97f5e3a309  /patched-lib/libnvidia-encode.so.460.32.03
Patched!
/
```
![Screenshot_2021-01-31_19-24-24](https://user-images.githubusercontent.com/8075196/106390607-33628300-63fa-11eb-964e-730478fc677e.png)
Glad to send more data but I don't know what exactly can help

**Comment by jfinkel** [comment]
With many thanks for your hard work, I report that I am experiencing exactly the same phenomenon.  OBS is the source and, since the machine I am running on has no support for _nvenc_, I am using the x264 software encoder. Being entirely new to this, I'm not sure what I can do to assist in debugging and fixing the issue.  The /stats page looks quite similar to the one posted by dv4mp1r3.

**Comment by TareqAlqutami** [comment]
> With many thanks for your hard work, I report that I am experiencing exactly the same phenomenon. OBS is the source and, since the machine I am running on has no support for _nvenc_, I am using the x264 software encoder. Being entirely new to this, I'm not sure what I can do to assist in debugging and fixing the issue. The /stats page looks quite similar to the one posted by dv4mp1r3.

@jfinke and @dv4mp1r3 , this issue seems to happen for those using nvenc, I can't replicate the issue because I don't have a machine that supports it.

@jfinkel, for your case, since you use x264, you should use the other dockerfiles or just pull from docker hub.

did you try this:
`docker run -d -p 1935:1935 -p 8080:8080 alqutami/rtmp-hls:latest`
