### ISSUE TITLE
error 405 when streaming in DASH or HLS

### ISSUE THREAD

**Issue by chache35** [TareqAlqutami/rtmp-hls-server#16]
Hello, 

I'm unable to stream to the nginx server whatever the format (DASH, or HLS) : A 405 error is raised for the PUT request
Docker logs : 
172.29.31.13 - - [15/Dec/2020:16:44:00 +0000] "PUT /hls/file-TL_11-6.m3u8 HTTP/1.1" **405** 157 "-" "v4.1"
172.29.31.13 - - [15/Dec/2020:16:44:00 +0000] "PUT /dash/audio-TL_11-6-24000-160805064.mp4a HTTP/1.1" **405** 157 "-" "v4.1"

**Comment by TareqAlqutami** [comment]
Are you trying to stream DASH/HLS to the Nginx or stream DASH/HLS from nginx? Can you detail out how you are doing it
The default Nginx config is to push RTMP stream to the server and playback RTMP/DASH/HLS.

**Comment by chache35** [comment]
Hi,

I'm trying to push HLS and DASH to Nginx.
If Nginx is only able to ingest RTMP, that is probably why it doesn't work.

**Comment by TareqAlqutami** [comment]
Yes, the current Nginx only ingests RTMP then playbacks RTMP or DASH/HLS. 
To put HLS/DASH streams, you may need to configure Video On Demand (VOD). I am not sure how Nginx can be configured to write the files without an additional web application.

**Comment by chache35** [comment]
Thank you.
I have finally found a configuration that also manage DASH and HLS in PUT mode
