### ISSUE TITLE
hls issue

### ISSUE THREAD

**Issue by rumbis** [TareqAlqutami/rtmp-hls-server#2]
hls is not working on ip

**Comment by TareqAlqutami** [comment]
Hello @rumbis,
Sorry for taking long to reply.
Can you describe in details the issue.
If you want to confirm HLS fragments are generated:
 - go into the docker container: ` docker exec -it <container_name> bash `
 - list the content of mnt/hls ` ls mnt/hls/`
 - if you find steams .m3u8 and .ts files, it means HLS is working.
 - you can play the HLS content using `http://<server IP>:8080/hls/<stream-key>.m3u8`
If you were referring to playing hls using HLS player provided. It is hard-coded to play the content from `http://127.0.0.1:8080/hls/test.m3u8`. You can download the player from github and modify it then attach to the docker container using
`  docker run -d -p 1935:1935 -p 8080:8080 -v custom_players:/usr/local/nginx/html/players alqutami/rtmp-hls`

**Comment by rumbis** [comment]
Thank you very much I was able to find that now I'm trying to make it work on https  with domain name it's fine to add the port 443?

**Comment by TareqAlqutami** [comment]
It is possible to have secured HLS. You will need to modify nginx.conif. You can mount HTML/certificates and the modified config file to the container using -v. Don't forget to expose port 443 using -p 443:443
