### ISSUE TITLE
Add drop_idle_publisher 10s; to conf

### ISSUE THREAD

**Issue by andostini** [TareqAlqutami/rtmp-hls-server#22]
I would recommend adding the drop_idle_publisher 10s; after the exec push to the nginx conf to prevent errors when the stream publisher has network issues.

How to reproduce: 
Stream to nginx via OBS and pull network cable of your streaming device. When reconnecting you cannot stream to the same Streamkey. error_log says: live: already publishing. 

The above directive fixes this problem.

**Comment by TareqAlqutami** [comment]
Thanks for the suggestion. I added the drop_idle_publisher to master.
