### ISSUE TITLE
HLS / MPD browser blocked mix content

### ISSUE THREAD

**Issue by WyattYung** [TareqAlqutami/rtmp-hls-server#23]
When I use dashjs or hls.js to embed hls/mpd url into a https webpage
eg.
http://localhost:8080/dash/test_src.mpd
http://localhost:8080/hls/test.m3u8

browser was blocked the file, and the error msg is:
"This request has been blocked; the content must be served over HTTPS."

How to make http to https as browser blocked mix content

**Comment by bharathmsd7** [comment]
> When I use dashjs or hls.js to embed hls/mpd url into a https webpage
> eg.
> http://localhost:8080/dash/test_src.mpd
> http://localhost:8080/hls/test.m3u8
> 
> browser was blocked the file, and the error msg is:
> "This request has been blocked; the content must be served over HTTPS."
> 
> How to make http to https as browser blocked mix content



> When I use dashjs or hls.js to embed hls/mpd url into a https webpage
> eg.
> http://localhost:8080/dash/test_src.mpd
> http://localhost:8080/hls/test.m3u8
> 
> browser was blocked the file, and the error msg is:
> "This request has been blocked; the content must be served over HTTPS."
> 
> How to make http to https as browser blocked mix content

Make ssl on in nginx.conf and add your ssl certificates to it.
