### ISSUE TITLE
No logs for incoming rtmp connections to say what went wrong

### ISSUE THREAD

**Issue by pinkfish** [TareqAlqutami/rtmp-hls-server#3]
I don't see any logs at all for connections on the 1935 port.  It doesn't log it started/stopped/failed anything at all in the logs.  Is it supposed to?  Is there something I can add so it does log something?  Right now it is disconnecting immediately and not saying why.

**Comment by TareqAlqutami** [comment]
hello @pinkfish,

You can access the logs directly from outside the container using docker logs.
`docker logs -f <container_name>`
The logs inside the container are in ` var/log/nginx/` 

You can also check the connection using the stats page `http://<server-ip>:8080/stats`
If there is an issue from the media server, it should show in these logs.

**Comment by pinkfish** [comment]
Ahhh.  THanks!
