### ISSUE TITLE
URL-Path in dockerfile does not exist anymore.

### ISSUE THREAD

**Issue by DigibitDK** [TareqAlqutami/rtmp-hls-server#31]
In your Dockerfiles, you refers to:
wget https://github.com/arut/nginx-rtmp-module/archive/v${NGINX_RTMP_MODULE_VERSION}.tar.gz

That path do not exist anymore, since 'archive' has been removed.

I guess the correct path is now:
wget https://github.com/arut/nginx-rtmp-module/archive/refs/tags/v${NGINX_RTMP_MODULE_VERSION}.tar.gz

It might be time to update NGINX, FFMPEG and RTMP-module-versions and Debian-version as well :)

**Comment by TareqAlqutami** [comment]
I just rebuilt the docker image again and everything is still fine. The paths to all the packages are actually still available
The current version for rtmp is set to 1.2.1 and you can download it:
wget https://github.com/arut/nginx-rtmp-module/archive/v1.2.1.tar.gz

I recall last time I tried to update ffmpeg but the build seems to fail, some conflict I guess.
Pull requests are welcome though.

**Comment by DigibitDK** [comment]
Interesting, normally I just browse github.com/arut/nginx-rtmp-module/archive/ to see what version that is latest, but since I was not able to do that, I just expected that it did not work anymore :D 

I have created your docker with NGINX 1.21.4, RTMP 1.2.2 and FFMPEG 4.4.1 and did not notice any fatal errors, and things seems to work - (I have videos that uses the FFMPEG module)

(I downloaded your github, edithed Dockerfile with new versions, and build it just fine - But I do encounter issues with using newest Debian)
