### ISSUE TITLE
How to run on Raspberry Pi 4 with OpenWrt

### ISSUE THREAD

**Issue by DerRheingold** [TareqAlqutami/rtmp-hls-server#34]
Hi,
your Docker container is exactly what I'm looking for 🤩 My project is to have a Raspberry Pi 4 as a wireless Accesspoint running a Streaming-Server so that I can stream a drone video live onto multiple devices.

For the Access Point I'm using OpenWRT (as Raspian was not reliable with an external wifi-antenna). I got docker set up for OpenWrt however when I try to run the container via
`docker run --platform linux/arm64 -d -p 1935:1935 -p 8080:8080 alqutami/rtmp-hls`
after the download I gt this message back:
`WARNING: image with reference alqutami/rtmp-hls was found but does not match the specified platform: wanted linux/arm64, actual: linux/amd64
docker: Error response from daemon: image with reference alqutami/rtmp-hls was found but does not match the specified platform: wanted linux/arm64, actual: linux/amd64.`

What must I do to get it up and running?

Thanks a lot in advance! :)

**Comment by Matho** [comment]
Hi @DerRheingold 

I have opened pull request with support for `aarch64` platform (`linux/arm64/v8`) . Check this pull request https://github.com/TareqAlqutami/rtmp-hls-server/pull/39 for more info. 

The problem you had is, that currently this repo supports only `linux/amd64` architecture and not `linux/arm64` . 

Also, in the mentioned pull request you can find link to prebuilded docker image for aarch64 architecture.

Martin

**Comment by TareqAlqutami** [comment]
Hello @Matho,
Thank you for your contribution, I will review and merge if no issues.
The existing builds don't have built containers for arm arch as you have figured out. I did build it locally and it worked after doing similar modifications to your PR.

Tareq
