### ISSUE TITLE
how to enable user pass for OBS?

### ISSUE THREAD

**Issue by siavashfazli** [TareqAlqutami/rtmp-hls-server#36]
Hi dear!
I need to set a user pass for my specific stream key to restrict others to access my stream key.
How can I enable authorization??

**Comment by TareqAlqutami** [comment]
Hello @siavashfazli ,
I think stream auth doesn't come natively with rtmp module. It requires an additional package to do it. I never used it myself but here are some packages that can be added to do the job:
- https://github.com/Nesseref/nginx-rtmp-auth
- https://github.com/voc/rtmp-auth

**Comment by siavashfazli** [comment]
@TareqAlqutami Thank you, I'll check them.
