### ISSUE TITLE
share my screen

### ISSUE THREAD

**Issue by chongma** [TareqAlqutami/rtmp-hls-server#8]
Hi,

Thanks for the package it is easy to install and works well.  

The aim was to use this to just share my desktop to others using OBS.  However when I watch the stream on the web players or on VLC it doesn't show the live stream but a slightly out of date one.

I don't want to save any video to the server.  I just want a live stream that shows only the latest.  Otherwise it won't make any sense to anyone.  Is there any way to do that?

**Comment by TareqAlqutami** [comment]
Sorry for late reply,
May I know what is the latency of the live stream? RTMP can have a latency from 2-10 seconds depending on many factors.
Based on my testing, I get around 2-3 seconds latency.
If you need low latency, you may need to use webRTC protocol.
Have a look at this article:
[https://www.wowza.com/blog/streaming-protocols-latency](https://www.wowza.com/blog/streaming-protocols-latency)

**Comment by chongma** [comment]
Thanks Tareq.  I switched to using an online meeting app instead.  It was easy to use your server.
